### ISSUE TITLE
Momento Spams Music Error Message when typing any command in Private Messages

### ISSUE THREAD

**Issue by timmy-time** [momentodevs/Momento#2]
When typing `m?help` in dms, Momento seems to act strange and just infinitely spam the users dm's with `Music commands are not available in Private Messages.`. There is a solution but that would require to rewrite the whole of [error_handler.py](https://github.com/timmy-time/Momento/blob/master/cogs/error_handler.py). if any users can help contribute towards this bug, it would be appreciated.

**Comment by timmy-time** [comment]
To add, please don't Direct Message Momento with any command at this point of time. for now I will be disabling DM replies until this issue is resolved.

**Comment by timmypidashev** [comment]
Fixed Dms bug. Not sure if my commit shows up globally thou, DM me if you dont see it.
